version: '3.7'

services:
  mysql:
    image: mysql:oracle
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mysqlpw
      MYSQL_DATABASE: engagexr
    ports:
      - '3306:3306'
    networks:
      - backend
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mysql
    depends_on:
            mysql:
                condition: service_healthy


networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
