tags:
- name: auth
  description: auth API
- name: users
  description: users API
- name: employees
  description: employees API
- name: companies
  description: companies API

paths:
# [POST] login
 /login:
  post:
    tags:
    - auth
    summary: login
    parameters:
    - name: body
      in: body
      description: user Data
      required: true
      schema:
        $ref: '#/definitions/users'
    responses:
      200:
        description: 'OK'
      400:
        description: 'Bad Request'
      500:
        description: 'Server Error'
# [POST] signup
  /signup:
    post:
      tags:
      - auth
      summary: Add new User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
# [GET] users
  /users:
    get:
      tags:
      - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] users
    post:
      tags:
      - users
      summary: Add User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] users/id
  /users/{id}:
    get:
      tags:
      - users
      summary: Find User By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      tags:
      - users
      summary: Update User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      tags:
      - users
      summary: Delete User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] companies
  /companies:
    get:
      tags:
      - companies
      summary: Find All Companies
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] companies
    post:
      tags:
      - companies
      summary: Add Company
      parameters:
      - name: body
        in: body
        description: company Data
        required: true
        schema:
          $ref: '#/definitions/companies'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] companies/id
  /companies/{id}:
    get:
      tags:
      - companies
      summary: Find Company By Id
      parameters:
      - name: id
        in: path
        description: Company Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] companies/id
    put:
      tags:
      - companies
      summary: Update Company By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      - name: body
        in: body
        description: company Data
        required: true
        schema:
          $ref: '#/definitions/companies'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] companies/id
    companies:
      tags:
      - users
      summary: Delete Company By Id and all the Employees asociates to this Company
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] employees
  /employees:
    get:
      tags:
      - employees
      summary: Find All Employees
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] employees
    post:
      tags:
      - employees
      summary: Add Employees
      parameters:
      - name: body
        in: body
        description: employee Data
        required: true
        schema:
          $ref: '#/definitions/employees'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] employees/id
  /employees/{id}:
    get:
      tags:
      - employees
      summary: Find Employee By Id
      parameters:
      - name: id
        in: path
        description: Employee Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] employees/id
    put:
      tags:
      - employees
      summary: Update Employee By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
        type: integer
      - name: body
        in: body
        description: company Data
        required: true
        schema:
          $ref: '#/definitions/employees'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] employees/id
    companies:
      tags:
      - employees
      summary: Delete Employee
      parameters:
      - name: id
        in: path
        description: employee Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'


# definitions
definitions:
  users:
    type: object
    required:
        - email
        - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
  employees:
    type: object
    required:
        - firstName
        - lastName
        - companyId
    properties:
      firstName:
        type: string
        description: employee first name
      lastName:
        type: string
        description: employee last name
      companyId:
        type: number
        description: company Identifier
      email:
        type: string
        description: employee email
      phone:
        type: string
        description: employee phone
  companies:
    type: object
    required:
        - name
        - email
        - phone
        - website
    properties:
      name:
        type: string
        description: company name
      email:
        type: string
        description: company email
      phone:
        type: string
        description: company phone
      website:
        type: string
        description: company website


schemes:
 - http
